### ISSUE TITLE
Automatically prebuild devcontainer(s)

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#1009]
See #1001 

Configure pre-building for both the default (bazel) and cmake codespace, probably easiest to have it work on the same schedule as the nightlies. Settings are at https://github.com/google/heir/settings/codespaces

**Comment by AlexanderViand-Intel** [comment]
@j2kun with the devcontainer.json files merged, can you please enable prebuilding for both of them? Thanks!

**Comment by j2kun** [comment]
Set up, here's the first build: https://github.com/google/heir/actions/runs/11222479029/job/31195006849

**Comment by AlexanderViand-Intel** [comment]
Seems to work great for bazel (default devcontainer.json) 👍 but not yet for cmake? 
I'll go ahead and throw up a PR for actually enabling LLVM/HEIR building in just the bazel container in the meantime :)

**Comment by j2kun** [comment]
Ah, I have to create a second pre build for cmake, sorry. I can do that shortly.

**Comment by j2kun** [comment]
Done; https://github.com/google/heir/actions/runs/11244478911/job/31262639233

**Comment by j2kun** [comment]
FYI I disabled the CMake dev container prebuild since it has been failing for quite a while now. I am tempted to disable the bazel one as well until we know someone who is actually using it.

**Comment by AlexanderViand-Intel** [comment]
Thanks for the update! The CMake fixes are unfortunately non-trivial and hard to justify doing right now :(
However, the bazel one  I "dogfood" quite regularly for reviews and work on the go, though it might be more sustainable CI-time-wise to set it to once a day, same time as the nightly, rather than on each push?

**Comment by j2kun** [comment]
As long as you're using it I'm fine leaving it as-is.
