### ISSUE TITLE
bgv: Add verifiers for BGV ops

### ISSUE THREAD

**Issue by asraa** [google/heir#101]
It would be nice to add verifiers to BGV ops that can perform functionality like:
1. Verify that a multiplication operation's inputs have the same number of polys, and its output's number of polys is increased.
2. Verify that addition operations' inputs have the same number of polys 
3. Verify that a relinearize inputs and outputs are valid based on the `from_basis` and `to_basis`.
4. Verify that a modulus switch's `from_level` and `to_level` are decrementing and also valid indices in the `#rings` of the input ciphertext.

I'm not sure whether these exist better and verifiers on the types, or belong to a single high level BGV validation pass.

**Comment by mr0re1** [comment]
2. ~~Verify that addition operations' inputs have the same number of polys~~

Achieved by using `SameOperandsAndResultType` trait.
