### ISSUE TITLE
website: Pick a custom domain name for the website

### ISSUE THREAD

**Issue by j2kun** [google/heir#102]
heir.dev is taken, so I browsed a list https://domains.google.com/registrar/search?searchTerm=heir.dev&hl=en&tab=1

Some fun ones:

- heir.day
- heir.band
- heir.software
- heir.tools
- heir.style

**Comment by j2kun** [comment]
Also some other ones like `heir-fhe.dev` are available, but I feel like shorter is always better.

**Comment by asraa** [comment]
+1 for `heir.tools`!

**Comment by mr0re1** [comment]
+1 for `heir.style`

**Comment by AlexanderViand-Intel** [comment]
Did you come to a conclusion on this? If not, I suggest we pick one at todays meeting.

**Comment by j2kun** [comment]
Looks like `heir.dev` is now available.

**Comment by AlexanderViand-Intel** [comment]
🎉 Good things come to those who wait, I guess..
Let's go for that then?
