### ISSUE TITLE
poly: lower poly.add and poly.mul

### ISSUE THREAD

**Issue by j2kun** [google/heir#104]
Initial poly lowering pass shell added in https://github.com/google/heir/pull/94

**Comment by asraa** [comment]
For the sake of testing and making sure Poly is workable, I'm giving this a stab, started with naive implementation of `poly.add`.

**Comment by j2kun** [comment]
I'll take poly.mul

**Comment by j2kun** [comment]
Fixed by https://github.com/google/heir/pull/180, and we're just waiting for internal checks to pass before merging.
