### ISSUE TITLE
chore: use PR labels to indicate final merge status

### ISSUE THREAD

**Issue by asraa** [google/heir#107]
Because of internal requirements, we require that PRs be squashed into a single commit before being merged. Currently, this is implemented with a pr_style workflow that checks the number of commits. However, enforcing this during the review process makes it difficult to see changes after comments are addressed.

Instead, we may want to allow the author to keep multiple commits (and potentially disallow merge commits to make this easier), and simply require a squash at the end of the review process.

**Comment by AlexanderViand-Intel** [comment]
Closing, as this seems to have been achieved with the current workflow (c.f. https://google.github.io/heir/docs/contributing/)
