### ISSUE TITLE
Annotate management operations for BGV/CKKS

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [google/heir#1091]
I was trying to insert relinearize/modreduce operations using analysis for optimization purpose, and find that after the current `secret-to-<scheme>` lowering it is hard to manipulate the IR (especially we are migrating lwe types; also check #860). Instead we can place these management ops in secret dialect.

For example, the current lazy relinearization pass is implemented in bgv dialect, it can be also applied to ckks. Also, that pass needs to worry about LWE types, which should be handled by lowering passes.

I wrote a demo using the current depth analysis in my [fork](https://github.com/ZenithalHourlyRate/heir/commit/b9a34f58c30a6de8a69ea575990a93ab15a920ec)

```mlir
module {
  func.func @func(%arg0: !secret.secret<i16>, ...) {
    %0 = secret.generic ins(...
    ^bb0(%arg8: i16, ...):
      %1 = arith.muli %arg8, %arg9 {depth = 1 : i64, lhs = 0 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %2 = arith.muli %1, %arg10 {depth = 2 : i64, lhs = 1 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %3 = arith.muli %2, %arg11 {depth = 3 : i64, lhs = 2 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %4 = arith.muli %3, %arg12 {depth = 4 : i64, lhs = 3 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %5 = arith.muli %4, %arg13 {depth = 5 : i64, lhs = 4 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %6 = arith.muli %5, %arg14 {depth = 6 : i64, lhs = 5 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      %7 = arith.muli %6, %arg15 {depth = 7 : i64, lhs = 6 : i64, relin = 3 : i64, rhs = 0 : i64} : i16
      secret.yield %7 : i16
    } -> !secret.secret<i16>
    return %0 : !secret.secret<i16>
  }
}
```

If such direction is favored, the following stpes can be done

Relinearize part

* Modify `SecretGenericOpMulConversion` to emit `RelinearizeOp` as needed.
* Modify `OptimizeRelinearization` to work on secret dialect, so that it does not need to worry about LWE types.

Modswitch/Rescale part

* For modreduce, emit corresponding `ModReduceOp` according to operand/result depth annotation (namely the simple auto mod reduce technique), so that we do not need to rely on openfhe for level management (openfhe backend now defaults to the FLEXIBLEAUTOEXT scaling technique).
* Further optimization can be implemented upon this. And they dont need to worry about LWE types.
* Note that there are also other management ops like `upscale` for CKKS and various CKKS compiler has explored scale management. Such infra could be used to implement them.

**Comment by j2kun** [comment]
Could you say more about what you were trying to do and the difficulties you ran into?

I'm not sure I would agree that the ciphertext management ops should be in the secret dialect, primarily because that leaks abstraction across dialect boundaries (secret is scheme-agnostic, but relinearization is scheme-specific), and second because I expect the relinearization optimization to later incorporate more scheme-specific concepts like being aware of the noise impact of inserting relin ops.

My main idea to generalize the relin optimization pass is to add traits and interfaces to the relevant scheme ops, and modify the pass to operate on ops via their interfaces. This would also allow different scheme dialects to return extra information from their interface implementations that correspond to stuff like noise modeling differences between schemes.

**Comment by ZenithalHourlyRate** [comment]
> being aware of the noise impact of inserting relin ops.

I'm actually working on this, using average-case noise analysis (based on your old PR) to select a viable (noise allowed) and possibly minimal (implemented a cost model) param set and operation graph. I will eventually upstream it, starting from common parts like cost model.

Here is some initial result of it (finally get it end to end), you may check it [here] (https://github.com/ZenithalHourlyRate/heir/compare/ddfddb4f50131b5b25e080a65e187b00c2dc6611...ZenithalHourlyRate:eval-noise-v1) with `main/run.sh`

Analysis selected param and noise estimation
```
INFO: Running command line: bazel-bin/tools/heir-opt '--mlir-to-secret-arith=entry-function=func' --operation-balancer --annotate-secret-management --validate-noise '--debug-only=ValidateNoise' '--mlir-to-openfhe-bgv=entry-function=func ciphertext-degree=8' main/func.mlir
Selected Param: Param: n = 8192, L = 2, relinDeg = 2, qi = [55, 55, 55, ], digitSize = 30, dnum = 0, alpha = 0, pi = []
<block argument> of type 'i16' at index: 0: enc bound 26.79
<block argument> of type 'i16' at index: 1: enc bound 26.79
<block argument> of type 'i16' at index: 2: enc bound 26.79
<block argument> of type 'i16' at index: 3: enc bound 26.79
<block argument> of type 'i16' at index: 4: enc bound 26.79
<block argument> of type 'i16' at index: 5: enc bound 26.79
%1 = arith.muli %arg8, %arg9 : i16: mult bound 57.67
%1 = arith.muli %arg8, %arg9 : i16: relin bound 57.75
%2 = arith.muli %1, %arg10 : i16: mult bound 88.64
%2 = arith.muli %1, %arg10 : i16: modd bound 33.64
%2 = arith.muli %1, %arg10 : i16: relin bound 55.79
%3 = arith.muli %arg11, %arg12 : i16: mult bound 57.67
%3 = arith.muli %arg11, %arg12 : i16: relin bound 57.75
%4 = arith.muli %3, %arg13 : i16: mult bound 88.64
%4 = arith.muli %3, %arg13 : i16: relin bound 88.64
%4 = arith.muli %3, %arg13 : i16: modd bound 33.64
%5 = arith.muli %2, %4 : i16: mult bound 93.52
%5 = arith.muli %2, %4 : i16: relin bound 93.52
%5 = arith.muli %2, %4 : i16: modd bound 38.52
```

OpenFHE lowering and running result, with actual noise.
```
Element Parameters: ILDCRTParams [m=16384 n=8192 q=46767924130724242010584182085469215285039268954113 ru=0 bigq=0 bigru=0]
  m_params:
    0: ILParams [m=16384 n=8192 q=36028793789300737 ru=1134974017364 bigq=0 bigru=0]
    1: ILParams [m=16384 n=8192 q=36028786272993281 ru=603296523949 bigq=0 bigru=0]
    2: ILParams [m=16384 n=8192 q=36028712183676929 ru=8581620453067 bigq=0 bigru=0]
  m_originalModulus: 0

Encoding Parameters: [p=65537 rootP =0 bigP =0 rootBigP =0 g=0 L=8192]

v28=Encrypt v24, v27    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.7879 budget 138.212
v35=Encrypt v31, v34    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 26.007 budget 137.993
v42=Encrypt v38, v41    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.9658 budget 138.034
v49=Encrypt v45, v48    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.9233 budget 138.077
v56=Encrypt v52, v55    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.8424 budget 138.158
v63=Encrypt v59, v62    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.9069 budget 138.093
v70=Encrypt v66, v69    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.7699 budget 138.23
v77=Encrypt v73, v76    cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 25.9644 budget 138.036
v9=EvalMultNoRelin v1, v2       cv 3 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 56.5308 budget 107.469
v10=Relinearize v9      cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 57.056 budget 106.944
v11=EvalMultNoRelin v10, v3     cv 3 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 87.3554 budget 76.6446
v12=ModReduce v11       cv 3 Ql 2 logQ: 110 logqi: [ 55 55 ] noise: 32.4083 budget 76.5917
v13=Relinearize v12     cv 2 Ql 2 logQ: 110 logqi: [ 55 55 ] noise: 54.6418 budget 54.3582
v14=EvalMultNoRelin v4, v5      cv 3 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 56.6178 budget 107.382
v15=Relinearize v14     cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 56.7794 budget 107.221
v16=EvalMultNoRelin v15, v6     cv 3 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 87.4168 budget 76.5832
v17=Relinearize v16     cv 2 Ql 3 logQ: 165 logqi: [ 55 55 55 ] noise: 87.4168 budget 76.5832
v18=ModReduce v17       cv 2 Ql 2 logQ: 110 logqi: [ 55 55 ] noise: 32.4164 budget 76.5836
v19=EvalMultNoRelin v13, v18    cv 3 Ql 2 logQ: 110 logqi: [ 55 55 ] noise: 93.5568 budget 15.4432
v20=Relinearize v19     cv 2 Ql 2 logQ: 110 logqi: [ 55 55 ] noise: 93.5568 budget 15.4432
v21=ModReduce v20       cv 2 Ql 1 logQ: 55 logqi: [ 55 ] noise: 38.5568 budget 15.4432
```

Now here is the ugly part:

It was first implemented on bgv dialect, as the implemented analysis is bgv-specific. Then I found that it is hard to manipulate bgv IR, especially we are migrating LWE types. I think those type constraint (rlweparams.dimension, basis) should be cared by the lowering pass, and optimization pass should care less about them. Over-early over-specified type will add burden to optimization pass writers.

So I migrated to the title suggested approach: using attr on the operation and lowering pass will lower them accordingly. Unfortunately we do not have a bgv.bgv type (with such type we can have a clean computation graph without LWE types, and the pipeline can be `--mlir-to-secret-arithmetic --secret-to-bgv-type --optimization-pass --bgv-type-to-lwe --bgv-lwe-to-openfhe`) so I have to do it directly on secret dialect.

Result of `--mlir-to-secret-arithmetic --operation-balancer --annotate-secret-management --validate-noise`

```mlir
module {
  func.func @func(%arg0: !secret.secret<i16>, ...) -> !secret.secret<i16> attributes {digitSize = 30 : i64, keySwitchTechnique = "BV", maxRelinSkDeg = 2 : i64, multiplicativeDepth = 2 : i64, numLargeDigits = 0 : i64, plaintextModulus = 65537 : i64, ringDim = 8192 : i64, scalingModSize = 55 : i64} {
    %0 = secret.generic ins(%arg0, ... : !secret.secret<i16>) attrs = {depth = 3 : i64} {
    ^bb0(%arg8: i16, ...):
      %1 = arith.muli %arg8, %arg9 {mgmt = ["relin"]} : i16
      %2 = arith.muli %1, %arg10 {mgmt = ["modd", "relin"]} : i16
      %3 = arith.muli %arg11, %arg12 {mgmt = ["relin"]} : i16
      %4 = arith.muli %3, %arg13 {mgmt = ["relin", "modd"]} : i16
      %5 = arith.muli %2, %4 {mgmt = ["relin", "modd"]} : i16
      secret.yield %5 : i16
    } -> !secret.secret<i16>
    return %0 : !secret.secret<i16>
  }
}
```

Now the hacky part:

The above are about lowerings. For param passing through all the way down to openfhe, now I have to tag those attr on `FuncOp` so `--openfhe-configure-crypto-context` can get the information. Do you have suggestion on how to share information between passes?

**Comment by j2kun** [comment]
> Do you have suggestion on how to share information between passes?

For cryptosystem parameter selection I think this will be a rather important topic, and I don't know exactly what we'll do long term, especially considering the possibility of scheme switching, in which we'll have multiple sets of parameters floating around. It may make sense at some point to have a region-holding op that is annotated with the parameters that apply to that region. But until we get to the point where we need it, I think a safe approach would be to annotate the `moduleOp` with attributes. Maybe bundle them in a sensible way under a single parent attribute (say, `BGVParametersAttr`) so that it's easier to move it around.

As for the rest, I think you should feel free to put attributes on ops in any dialect ad hoc, but you wouldn't be able to assume they persist across optimization passes and lowerings. They are preserved in a "best effort" manner, especially by upstream passes, and anything which rewrites ops will not be guaranteed to pass along attributes from the ops that are erased. The best approach is to organize your work such that the analysis that adds the attributes can be run within the same pass that actually does the work. If you need to keep op annotations around for a larger section of the pipeline, it may be hard to preserve them as the stages of the pipeline change.

I think there's a place for a high-level (maybe scheme agnostic) optimization pass that does ciphertext management, but I still think secret may not be the best long-term place for it.

Some other ideas that popped up in conversation:

- We could add a new dialect that contains dialect-agnostic ciphertext management ops (e.g., a `mgmt.relin` op that has `Any -> Any` type semantics) and insert them at the `secret.generic` level before being lowered to an FHE-specific dialect.
- We could create an intermediate dialect that represents the common abstractions over BGV, BFV, and CKKS (an "arithmetic FHE" dialect) that includes a ciphertext type that would fill the role of `bgv.bgv` as you mentioned earlier. This makes sense to me in that it could be the main place that some ciphertext parameters are selected, specifically those that are required to convert ciphertexts to LWE types.
- We could add sufficient helpers and abstractions to make the LWE types easier to work with. If the migration were completed, would you still find difficulty?

**Comment by ZenithalHourlyRate** [comment]
> * We could add sufficient helpers and abstractions to make the LWE types easier to work with. If the migration were completed, would you still find difficulty?

I think there are chicken-and-egg problems here. LWE type already contains all the parameter information (e.g. plaintext modulus, modulus chain, depth, encoding/packing method). The current ToBGV(actually ToLWE) lowering just use some default values. We should use some passes to decide them prior to it, instead of placing some placeholders then change them. Also, passes like deciding encoding/packing could totally change the structure of the circuit, then other parameters like depth/modulus would then need to be recalculated inside the pass to ensure a valid LWE IR. 

The natural logic should be "decide one param -> decide another -> generate/lower" instead of "generate/lowerWithDefault -> change param (bunch of other change) -> change circuit (then bunch of param change) -> change another param (then bunch of change)"

https://github.com/google/heir/blob/6d91164e43876b3b64cc952e367b188a859cfc59/lib/Dialect/Secret/Conversions/SecretToBGV/SecretToBGV.cpp#L47-L95

> * We could create an intermediate dialect that represents the common abstractions over BGV, BFV, and CKKS (an "arithmetic FHE" dialect) that includes a ciphertext type that would fill the role of `bgv.bgv` as you mentioned earlier. This makes sense to me in that it could be the main place that some ciphertext parameters are selected, specifically those that are required to convert ciphertexts to LWE types.

I agree with such reasoning.

**Comment by j2kun** [comment]
> Also, passes like deciding encoding/packing could totally change the structure of the circuit

I think we all agree this is the essential complexity here. I don't yet know what is the right order to choose all of these things. And I think there will be some decent amount of research one can do by changing the order of choices to enable a later choice to optimize differently based on assumptions of an earlier choice.

I think this bleeds into the way one writes an optimization pass for one or more of these choices (e.g., to allow ciphertext dimension to be chosen by the pass or assume it is fixed and known).

If one were forced to do this in LWE could essentially ignore the parts of the type they want to re-select when doing the analysis (effectively forming an in-memory "LWE" type with only the subset of fields they want to consider fixed), and then reconstruct all of the ops afterward with new LWE types matching the output of the pass. This would have the benefit of having all the different passes be more or less interchangeable in order.

If, by contrast, we add multiple intermediate dialects and "choose -> lower -> choose -> lower ..." then reordering the optimization passes becomes much harder, and we have the additional infrastructure of these extra dialects and lowerings to maintain. If we can manage to keep most of these kinds of passes at one granularity (either LWE or this hypothetical "abstracted arithmetic FHE dialect") then I think the system would remain flexible enough to change our minds later about ordering optimizations.

CC @asraa @AlexanderViand-Intel for any objections.

**Comment by ZenithalHourlyRate** [comment]
> discuss in the next open meeting

I'll demostrate it in more details in the next meeting

> the end goal of this work is to do parameter selection (at least a rough one at a high level).

Basically yes, but I think I am doing it in a more fine-grained manner. The current implemented method is, using average-case noise estimation (available paper gives underestimation though but I'm trying to fix them with different assumptions) to ensure for each ciphertext the noise wont blow up. And given such constraint, the extra bit the analysis has done is to try on different mgmt op placement (e.g. lazy relinearization/lazy modreduce), generating all possible schedules, and among all the schedules, select a minimal cost (with cost model) schedule, and this natually produces an "optimal" parameter for this circuit (minimize L, minimize Q, minimize N).

Also, the current searching algorithm is quite brutal; I will soon investigate how to use ILP for that.

I think in the future the optimization should also consider other schedule options like scale management (some paper, for CKKS), bootstrap op placement (e.g. DaCapo) and encoding/packing selection (lots of paper) and still many other considerations; Now I have not explored them yet, I think I'll do them in the next two or three steps.

> CKKS expert colleague who said he had an idea about how we might do parameter selection

I am curious about it. My current working direction is to migrate my current design (from BGV) to CKKS, as their noise model are somewhat similar, but faced a issue that their optimization goal is different (i.e. BGV only needs to ensure noise wont blow up, but the in-my-mind-hypothetical goal for CKKS is to ensure more precision, or given a precision requirement, select a param set/circuit (things become even more complex as there are security concerns like noise flooding))

**Comment by johannesmono** [comment]
For CKKS, I just want to point out Grafting (https://eprint.iacr.org/2024/1014) which simplifies modulus management significantly because it decouples the ciphertext modulus itself from the scaling factor. This also works for BGV (disclaimer: I've not checked the math in detail so maybe I'm missing something).

Food for thought: The more I think about it, the more convinced I am that use-case specific parameters are only worth the effort in LHE mode. Once we need bootstrapping, most of the modulus is used for that anyway and there's not much left to optimize for.

**Comment by ZenithalHourlyRate** [comment]
> Grafting (https://eprint.iacr.org/2024/1014)

Thank you! I'll look into this.

> Food for thought: The more I think about it, the more convinced I am that use-case specific parameters are only worth the effort in LHE mode. Once we need bootstrapping, most of the modulus is used for that anyway and there's not much left to optimize for.

I kind of agree. I have some arguments to mitigate this but I have not exprimented it yet so I'm not sure.

One thing I observe is that in the experiment the "schedule" above can sometime produce a circuit with less `MultiplicativeDepth`, namely `L'=L-1`, the circuit produced is similar to "Three-way Multiplications" in https://eprint.iacr.org/2012/099). One key advantage we have here is that we have kind-of-accurate noise estimation so we can concisely control the noise growth. I deem too-often mod reduce (where modreduce added-noise becomes dominant) will waste some noise space, from which we can profit. 

With this observation, it might be possible to optimize the circuit between bootstrapping, and as bootstrapping itself have placement problem (e.g. Dacapo), the in-between circuit can also be different subject to that placement and could be optimized, possibly reducing the total depth count. I have not exprimented so I do not know how much margin we can gain here. A even wilder try is to run the optimization on the bootstrap circuit itself. I'll definitely try it.
