### ISSUE TITLE
feat: Integrate tools to optimize circuits

### ISSUE THREAD

**Issue by asraa** [google/heir#111]
Related: https://github.com/google/heir/issues/110

We can take a high-level arithmetic program and create optimization passes that can invoke tools like Yosys and ABC to optimize and output a combinational circuit.

The combinational circuit can then be lowered to boolean FHE schemes.

**Comment by asraa** [comment]
See this other tool here: https://github.com/lsils/mockturtle

And some discussion about this here: https://discourse.llvm.org/t/integration-with-abc-optimizer/65264/2

**Comment by asraa** [comment]
I think it would be nice to go

Arith / other high-level -> Combinational logic block -> [ABC Transform] -> Optimized combinational logic block

Combinational logic can then be lowered to  schemes that support boolean gates / luts.

**Comment by asraa** [comment]
I also noticed this `ArithToCombPass` from CIRCT: 
https://github.com/llvm/circt/blob/main/include/circt/Transforms/Passes.td#L56C5-L71

**Comment by j2kun** [comment]
I think we can mark this one as fixed now.

**Comment by j2kun** [comment]
Reopening so we can migrate the TODOs to new issues
