### ISSUE TITLE
`--optimize-relinearization` crashing

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#1148]
@j2kun  While trying to add the `--optimize-relinearization` pass to the default RLWE pipeline, I've unfortunately hit some kind of issue:

`bazel run //tools:heir-opt -- --mlir-to-bgv=ciphertext-degree=8  --optimize-relinearization  $PWD/tests/Examples/openfhe/dot_product_8.mlir` 
says 
````
Error solving the problem: INVALID_ARGUMENT: duplicate name inserted: 
InsertRelin_bgv.rotate_loc("/home/aviand/code/heir/tests/Examples/openfhe/dot_product_8.mlir":1:1); ModelProto.variables are invalid
/home/aviand/code/heir/tests/Examples/openfhe/dot_product_8.mlir:1:1: error: Failed to solve the optimization problem```
then dumps the IR before actually crashing with 
```
heir-opt: external/llvm-project/llvm/include/llvm/ADT/DenseMap.h:204: const ValueT &llvm::DenseMapBase<llvm::DenseMap<mlir::Value, operations_research::math_opt::Variable>, mlir::Value, operations_research::math_opt::Variable, llvm::DenseMapInfo<mlir::Value>, llvm::detail::DenseMapPair<mlir::Value, operations_research::math_opt::Variable>>::at(const_arg_type_t<KeyT>) const [DerivedT = llvm::DenseMap<mlir::Value, operations_research::math_opt::Variable>, KeyT = mlir::Value, ValueT = operations_research::math_opt::Variable, KeyInfoT = llvm::DenseMapInfo<mlir::Value>, BucketT = llvm::detail::DenseMapPair<mlir::Value, operations_research::math_opt::Variable>]: Assertion `Iter != this->end() && "DenseMap::at failed due to a missing key"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
````
and dumping the stack.

In fact, if I dump the output of `--mlir-to-bgv=ciphertext-degree=8` into a file and then call heir-opt with `--optimize-relinearization` on that, it'll jump straight to the crashing/stack dump, not even emitting the error and IR...

**Comment by j2kun** [comment]
Acknowledged and reproduced. I will investigate tomorrow

**Comment by j2kun** [comment]
Another smell that is bizarre: when I dump the IR after `-secret-to-bgv` I get

```
!Z463187969_i32_ = !mod_arith.int<463187969 : i32>
#ring_Z463187969_i32_1_x8_ = #polynomial.ring<coefficientType = !Z463187969_i32_, polynomialModulus = <1 + x**8>>
!rlwe_ct = !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = #ring_Z463187969_i32_1_x8_>, underlying_type = tensor<8xi16>>
!rlwe_ct1 = !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = #ring_Z463187969_i32_1_x8_>, underlying_type = i16>
!rlwe_ct2 = !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <dimension = 3, ring = #ring_Z463187969_i32_1_x8_>, underlying_type = tensor<8xi16>>
module {
  func.func @dot_product(%arg0: !rlwe_ct, %arg1: !rlwe_ct) -> !rlwe_ct1 {
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c4 = arith.constant 4 : index
    %c7 = arith.constant 7 : index
    %0 = bgv.mul %arg0, %arg1 : (!rlwe_ct, !rlwe_ct) -> !rlwe_ct2
    %1 = bgv.relinearize %0 {from_basis = array<i32: 0, 1, 2>, to_basis = array<i32: 0, 1>} : !rlwe_ct2 -> !rlwe_ct
    %2 = bgv.rotate %1 {offset = 4 : index} : !rlwe_ct
    %3 = bgv.add %1, %2 : !rlwe_ct
    %4 = bgv.rotate %3 {offset = 2 : index} : !rlwe_ct
    %5 = bgv.add %3, %4 : !rlwe_ct
    %6 = bgv.rotate %5 {offset = 1 : index} : !rlwe_ct
    %7 = bgv.add %5, %6 : !rlwe_ct
    %8 = bgv.extract %7, %c7 : (!rlwe_ct, index) -> !rlwe_ct1
    return %8 : !rlwe_ct1
  }
}
```

Which then succeeds under `bazel run //tools:heir-opt -- --optimize-relinearization`

It is able to generate and solve the model without problem.

Based on the error message

```
INVALID_ARGUMENT: duplicate name inserted: InsertRelin_bgv.rotate_loc("/home/j2kun/fhe/heir/tests/Examples/openfhe/dot_product_8.mlir":1:1); ModelProto.variables are invalid
```

I suspect the problem is that I'm using the `loc` as the main "unique" part of the key in the variable name, but the locs are not really unique, and instead they're pointing to the first line of the original MLIR.

Maybe I can do better `loc` propagation, or maybe I can just force unique variable names with opaque identifiers (that harms debuggability though...)

**Comment by AlexanderViand-Intel** [comment]
Oh, I see! Yeah, I don't think using Locations for that is going to work, as there are, in addition to our stuff, upstream passes that will turn something into multiple ops all inheriting the same Location. 

If all you need is a unique identifier for each SSA `Value`, can you maybe use `Value` directly? Either see if there's some way to get the `%...` that it'd be assigned by the printer, or just using the pointer/memory address?

**Comment by j2kun** [comment]
Yeah, MLIR does not store SSA value names until the IR is printed. This is something I have run into quite a few times, and that's why I wrote the SelectVariableNames analysis. The memory address seems just as opaque as a random integer, so I'll see if I can come to a good compromise.

**Comment by ZenithalHourlyRate** [comment]
More reporting on this:

```mlir
func.func @add(%arg0: tensor<4xi16>, %arg1: tensor<4xi16>) -> tensor<4xi16> {
  %0 = arith.addi %arg0, %arg1 : tensor<4xi16>
  return %0 : tensor<4xi16>
}
```

The correct way to run the pipeline is ` --secretize --mlir-to-bgv=ciphertext-degree=4 `, but if with only `--mlir-to-bgv=ciphertext-degree=4`, we get

```
DenseMap::at failed due to a missing key
```
