### ISSUE TITLE
Where to access the tool "stablehlo-opt"

### ISSUE THREAD

**Issue by winnylyc** [google/heir#1160]
Hello, sorry for disturbing you.

I’m currently working on a simple pipeline that utilizes JAX as the frontend for HEIR, and I’m encountering difficulties when attempting to lower StableHLO to standard MLIR.

I noticed that a tool named "stablehlo-opt" is suggested to assist with this process in many issues like https://github.com/google/heir/issues/1079 https://github.com/google/heir/issues/954. However, I have no idea about where to obtain or access this tool.

May you give me some hint about how to access it? Or is it currently an internal tool?

Thank you for your help!

**Comment by j2kun** [comment]
You should be able to access it by building https://github.com/openxla/stablehlo from source and looking in `build/bin`. The main file for this binary is defined at https://github.com/openxla/stablehlo/blob/main/stablehlo/tools/StablehloOptMain.cpp (it's an MLIR project, so it should have a similar structure and organization to other MLIR-based projects, if you're familiar with that at all).

They also have python releases on their GitHub page, but I'm not sure if that supports a shim around `stablehlo-opt`.

**Comment by j2kun** [comment]
Also, it's no disturbance! If you are interested in using HEIR, please do let us know what you're working on, here or privately (on discord: the HEIR channel on https://discord.com/invite/fhe-org or you can DM any of the main contributors) and we will gladly assist you in your efforts.

**Comment by winnylyc** [comment]
Greatly appreciate your help! 
I will DM you for my current project. Thank you for your enthusiasm!
