### ISSUE TITLE
process: Improve process around PR merges

### ISSUE THREAD

**Issue by asraa** [google/heir#127]
Right now, it is challenging for an external contributor to note when a PR should get merged. I think we should do the following changes:

To enforce external review:
(1) Require an external LGTM for each PR
(2) Enable a process that indicates whether the mirrored internal PR has that external LGTM, and only merge if that condition is satisfied

JAX does something similar, where once a PR gets an LGTM from GitHub, they update the reviewers to something like `jax-mergeready`.

To help external contributors to understand the process, we should document the merge / contribution process.

This can also be used to solve https://github.com/google/heir/issues/107; we can gate the `-mergeready` review on having the commits squashed.

**Comment by j2kun** [comment]
I'd say just add the label manually for now. I like easy things.

**Comment by asraa** [comment]
Agree for now as well. I'll update the workflows!

**Comment by asraa** [comment]
Going to close for now, as the docs are updated. Feel free to open another one for any other process improvements
