### ISSUE TITLE
poly: extract_slice `InferTypeOpAdaptor` is wrong

### ISSUE THREAD

**Issue by mr0re1** [google/heir#130]
```mlir
error: 'poly.extract_slice' op inferred type(s) 'tensor<1024xui64, #poly.ring<cmod=2837465, ideal=#poly.polynomial<1 + x**1024>>>' are incompatible with return type(s) of operation 'tensor<2xi32>'
    %slice = poly.extract_slice(%p0, %c0, %c2) : (!poly.poly<#ring1>, index, index) -> tensor<2xi32>
```

It uses `poly.ring.ideal.degree` instead of difference of indexes to deduce shape.

Code: https://github.com/google/heir/blob/main/lib/Dialect/Poly/IR/PolyOps.cpp#L7

**Comment by mr0re1** [comment]
@j2kun  could you please confirm if my assessment is correct?

**Comment by j2kun** [comment]
That sounds right. An output slice should be the same size as the difference of the start/stop indices.

**Comment by j2kun** [comment]
I'll go ahead and fix this one.

**Comment by j2kun** [comment]
Hmmm an interesting twist: in this case extract_slice is given two index SSA values as arguments, which may not have statically known values. Would it make sense then, to use an unranked tensor type?

I'm also considering, for simplicity, changing them to static attributes for now, unless you think we need the variable-slice version for a WIP lowering.

**Comment by j2kun** [comment]
I almost think that it would be easier to just achieve extract_slice via to_tensor and then tensor.extract_slice.

**Comment by mr0re1** [comment]
> I almost think that it would be easier to just achieve extract_slice via to_tensor and then tensor.extract_slice.

+1 , let's avoid complexity and temptation to add more "tensor-like" ops, when it can be delegated to the `tensor` dialect.

**Comment by j2kun** [comment]
I also saw the op was not yet used anywhere, so I'll just remove it.

**Comment by mr0re1** [comment]
We could consider removing `GetCoeffOp` as well, as it can replaced with `to_tensor` + tensor op. Also it doesn't seem to have an intrinsic significance for the `poly` dialect.

**Comment by j2kun** [comment]
I will include this in a PR that adds to_tensor
