### ISSUE TITLE
rewrite pass to "booleanize": split multi-bit inputs and outputs

### ISSUE THREAD

**Issue by asraa** [google/heir#244]
Currently, the yosys optimizer uses `comb.extract` and `comb.concat` to deconstruct and reconstruct the inputs and outputs if they are multi-bit.

Example:
```
module {
  func.func @add_one(%arg0: i8) -> i8 {
    %0 = comb.extract %arg0 from 0 : (i8) -> i1
    %1 = comb.extract %arg0 from 1 : (i8) -> i1
    %false = arith.constant false
    %2 = comb.truth_table %0, %1, %false -> 6 : ui8
    %3 = comb.truth_table %0, %false, %false -> 1 : ui8
    %4 = comb.extract %arg0 from 2 : (i8) -> i1
    %5 = comb.truth_table %0, %1, %4 -> 120 : ui8
    %6 = comb.truth_table %0, %1, %4 -> 128 : ui8
    %7 = comb.extract %arg0 from 3 : (i8) -> i1
    %8 = comb.truth_table %6, %7, %false -> 6 : ui8
    %9 = comb.extract %arg0 from 4 : (i8) -> i1
    %10 = comb.truth_table %6, %7, %9 -> 120 : ui8
    %11 = comb.truth_table %6, %7, %9 -> 128 : ui8
    %12 = comb.extract %arg0 from 5 : (i8) -> i1
    %13 = comb.truth_table %11, %12, %false -> 6 : ui8
    %14 = comb.extract %arg0 from 6 : (i8) -> i1
    %15 = comb.truth_table %11, %12, %14 -> 120 : ui8
    %16 = comb.truth_table %11, %12, %14 -> 128 : ui8
    %17 = comb.extract %arg0 from 7 : (i8) -> i1
    %18 = comb.truth_table %16, %17, %false -> 6 : ui8
    %19 = comb.concat %18, %15, %13, %10, %8, %5, %2, %3 : i1, i1, i1, i1, i1, i1, i1, i1
    return %19 : i8
  }
}
```

However, in transpiling for FHE, we may actually *want* to change the function signature to deconstruct the multi-bit inputs into individual bits.

I assume the best way to do this may actually be a rewrite before passing to yosys optimizer, something that works on the secret or FHE level like "split inputs/booleanize".

**Comment by asraa** [comment]
Yeah, this is what I don't understand / can't figure out.

It technically breaks the invariant / caller contract. The other option I'm brainstorming is some kind of transform op that's a no-op in the current flow

**Comment by j2kun** [comment]
I think it makes sense to move the extract/concat outside the function call as a general pattern. The only difficulty there seems to be then the comb operations need to be further handled (converted to their arith or cggi counterparts?)

**Comment by asraa** [comment]
We could have the Yosys Optimizer pass create an internal function call that uses the extracted bits. We would then only lower the internal function call to CGGI.

> The only difficulty there seems to be then the comb operations need to be further handled (converted to their arith or cggi counterparts?)

I expect we're only interested in transpiling the inner function though, which maybe we can mark with some kind of attribute. I don't think we want to lower `comb.extract` to `cggi.bit_extract` - we just want to encrypt the inputs as bits. Or do you mean we should still lower through for sake of fully lowering the IR?

**Comment by j2kun** [comment]
If we're in the mode of just lowering the main entry function and converting the input to bits, you're right, it doesn't matter.  Though it may be worth replacing the function arguments with `tensor<ciphertext>` to keep the bits of the arguments grouped semantically.

What I meant instead was if we want more general support for something like this:

```
func.func @add_one(%arg0: i8) -> i8 {
  %0 = comb.extract %arg0 from 0 : (i8) -> i1
  %1 = comb.extract %arg0 from 1 : (i8) -> i1
  ...
  %19 = comb.concat ... : i1, i1, i1, i1, i1, i1, i1, i1
  return %19 : i8
}

func.func @caller() {
  %0 = arith.constant 7 : i8
  %1 = func.call @add_one(%0)
  ...
}
```

Then booleanizing would require changing it to this:

```
func.func @add_one(%arg0_0: i1, ..., %arg0_7: i1) -> (i1, i1, ..., i1) {
  return %foo, %bar, ...
}

func.func @caller() {
  %C = arith.constant 7 : i8
  %0 = comb.extract %C from 0 : (i8) -> i1
  %1 = comb.extract %C from 1 : (i8) -> i1
  ...
  %res0, ..., %res7 = func.call @add_one(%0, %1, ..., %7)
  %reconstructed_res = comb.concat %res0, ..., %res7 : i1, i1, i1, i1, i1, i1, i1, i1
  ...
}
```

And then we still have to deal with the comb.extract arguments on the other side of the call. In theory, those could be plain arith ops that are then lowered the normal way.

**Comment by asraa** [comment]
After writing up the different options
1. Extract and re-concatenate using `comb.extract` and `comb.concat` all inline (the current state)
2. Create an internal function that takes the extracted / concatenated inputs 
3. Use `tensor<8xi1>` to represent multi-bit integers like `i8`s and then tensor loads / inserts

I think (3) makes the most sense. Since like you mentioned, it keeps the ciphertexts semantically grouped together, and it will make it much easier to discern whether we are in the booleanized CGGI path or a shortint CGGI path.

Otherwise, we would only be able to tell we are in the boolean situation on whether there are internal ops that extract and concatenate the inputs.

IMO, it doesn't matter too much if we make the internal call at that point or not - codegenning would then map the loaded tensor values to vector accessors.

**Comment by j2kun** [comment]
I like `tensor<8xi8>`!
