### ISSUE TITLE
bgv : Add a verifier for Rotate

### ISSUE THREAD

**Issue by Maokami** [google/heir#287]
I believe there should be a check ensuring that the dimension of the ciphertext, which serves as the operand of rotation, is two.

Justification:
- SEAL throw an error when the above condition is violated:
https://github.com/microsoft/SEAL/blob/206648d0e4634e5c61dcf9370676630268290b59/native/src/seal/evaluator.h#L1046
- There's a bug in OpenFHE when the above condition is violated:
https://github.com/openfheorg/openfhe-development/issues/575

However, due to my lack of HE knowledge, I don't know why the rotation doesn't work when the dimension of ciphertext is greater than 2. Let me know if anyone knows!

**Comment by j2kun** [comment]
I will summarize the work needed to do this here, in case you are looking to dip your feet into the coding. A high-level explanation of how verifiers work is [here](https://jeremykun.com/2023/09/13/mlir-verifiers/).

- Add `let hasVerifier = 1;` to the BGV rotate op in [BGVOps.td](https://github.com/google/heir/blob/1a2ccfe22f2038638460f09442634e1768c8781d/include/Dialect/BGV/IR/BGVOps.td#L84)
- Add a new implementation of a function with signature `LogicalResult RotateOp::verify() { ... }` to [BGVDialect.cpp](https://github.com/google/heir/blob/1a2ccfe22f2038638460f09442634e1768c8781d/lib/Dialect/BGV/IR/BGVDialect.cpp)
- Add a lit test in [tests/bgv](https://github.com/google/heir/tree/1a2ccfe22f2038638460f09442634e1768c8781d/tests/bgv) that uses `--verify-diagnostics` to assert the appropriate error message is reported when verification fails. A good example is [here](https://github.com/google/heir/blob/1a2ccfe22f2038638460f09442634e1768c8781d/tests/secret/verifier.mlir#L1-L4)

**Comment by asraa** [comment]
> Let me know if anyone knows!

While I don't think it's theoretically impossible to apply a galois rotation on a length 3 ciphertext, I think the reason both implementations avoid doing so is because the Galois Keys are computed to switch the ciphertext from being encrypted from a key `(1, s^i)` to a `(1, s)`. If the ciphertext has length 3, then I'm not sure why there aren't static size checks, but the key switching matrix would only apply to the first two polys of the ciphertext and then probably leave an incorrect result.

**Comment by Maokami** [comment]
@j2kun @asraa Thank you for the pointers and explanations!

Before I start writing verifiers, I believe it's essential to establish the specification of the operations.

Based on this issue and [this conversation](https://github.com/google/heir/commit/cac99858ae94250935fa355ba9d9d88f1366f601#r133719677), it's challenging to determine which inputs are valid for each operation of the HE schemes. For instance, should we reject cases where `c1.dim != 2` in `mult(c1, c2)` and `rotate(c1)`?

One viable option is to follow the lead of existing libraries.
For rotations, to the best of my knowledge, SEAL, OpenFHE, and [Lattigo](https://github.com/tuneinsight/lattigo/blob/1f00f3ca7147a13f1313c64610385a904f84db7e/core/rlwe/evaluator_automorphism.go#L16C30-L16C30) all prohibit the case where `c.dim != 2`. Would it be acceptable to create a verifier based on these criteria?

**Comment by j2kun** [comment]
I think prohibiting `c.dim != 2` is acceptable. And generally speaking, my philosophy of software design is that it's better to start with a strict definition and relax it or generalize it only once you have a good reason to.

**Comment by j2kun** [comment]
Thanks again @Maokami! Please let me know if there is any other topic you want to work on in the project. I'm happy to help.
