### ISSUE TITLE
secret-distribute-generic does not support hello world model

### ISSUE THREAD

**Issue by asraa** [google/heir#319]
It seems there are a few different things that are coming up. The full secretized hello world model yields:

```
INFO: Running command line: bazel-bin/tools/heir-opt --secret-distribute-generic /usr/local/google/home/asraa/git/heir/tests/secret/hello_world.mlir
heir-opt: external/llvm-project/mlir/lib/IR/Block.cpp:188: void mlir::Block::eraseArgument(unsigned int): Assertion `index < arguments.size()' failed.
```

A shorter model 
```
func.func @affine_for(%arg0: !secret.secret<memref<1x80xi8>>) -> !secret.secret<memref<1x3x2x1xi8>> {
  %0 = secret.generic ins(%arg0 : !secret.secret<memref<1x80xi8>>) {
  ^bb0(%arg1: memref<1x80xi8>):
    %c-128_i8 = arith.constant -128 : i8
    %c0 = arith.constant 0 : index
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<1x3x2x1xi8>
    affine.for %arg2 = 0 to 3 {
      affine.for %arg3 = 0 to 2 {
        affine.store %c-128_i8, %alloc[%c0, %arg2, %arg3, %c0] : memref<1x3x2x1xi8>
      }
    }
    secret.yield %alloc : memref<1x3x2x1xi8>
  } -> !secret.secret<memref<1x3x2x1xi8>>
  return %0 : !secret.secret<memref<1x3x2x1xi8>>
}
```

brings:
```
error: type of return operand 0 ('memref<1x3x2x1xi8>') doesn't match function result type ('!secret.secret<memref<1x3x2x1xi8>>') in function @affine_for
  return %0 : !secret.secret<memref<1x3x2x1xi8>>
  ^
/usr/local/google/home/asraa/git/heir/tests/secret/test.mlir:14:3: note: see current operation: "func.return"(%2) : (memref<1x3x2x1xi8>) -> ()
```

which may have something to do with the memref allocation inside the secret body.

**Comment by j2kun** [comment]
I think this is a valid bug, but also I think you would want to run this pass with `--distribute-through=affine.for` to ensure the loop bodies are maintained as secret.

**Comment by asraa** [comment]
These are error messages with that option, it seems.

**Comment by asraa** [comment]
To be honest, I think the core reason is the complication of allocating a memref inside of the secret.generic - this needs to happen in hello world models (the returned value is a new memref of a different shape), and so somehow this allocated memref must be hoisted outside.

Right now, the memref allocation is preventing the affine.for for being the "first op" to split around.

**Comment by asraa** [comment]
Ah yes, this was filed before: https://github.com/google/heir/issues/306

I think there is still the non-distribute-through issue, but for now I'll close until we reach that case.

**Comment by j2kun** [comment]
I will add this as a test case to #306 because even after I finished implementing it, this still fails (though not with a segfault)
