### ISSUE TITLE
bgv: use LWE toolbox dialect for RLWE ciphertext types

### ISSUE THREAD

**Issue by asraa** [google/heir#487]
Right now, a BGV ciphertext holds on to a dimension (# of polys), a list of rings, and a level (describing which of the list of rings it belongs to). An LWE dialect RLWE ciphertext only holds on to an encoding and an RLWEparams attribute containing the N, cmod, and dim of the RLWE ciphertext.

To unify these, I'm inclined to make an LWE dialect RLWE ciphertext hold onto:
* The RLWE encoding (which differs between CKKS, BGV, BFV)
* A polynomial RingAttr (which described the ring attributes: like N and cmod)
* The dimension of the ciphertext

This would require:
* An individual BGV ciphertext no longer holds onto the global parameter data of which rings there are. The transformations for rings / dimension that happen during modulus or key switching will be encoded in their op attributes and will transform the ciphertext parameters.
* Decouple / remove the "RLWEParamsAttr" which previously bundled (cmod, N, and dim) and just use poly "RingAttr" and add a "dimension" to the RLWE ciphertext.

Links:
* BGV Ciphertext type: https://github.com/google/heir/blob/main/include/Dialect/BGV/IR/BGVTypes.td#L38-L42
* RLWE Ciphertext type: https://github.com/google/heir/blob/main/include/Dialect/LWE/IR/LWETypes.td#L45-L46
* RLWEParamsAttr: https://github.com/google/heir/blob/main/include/Dialect/LWE/IR/LWEAttributes.td#L319

**Comment by AlexanderViand-Intel** [comment]
I think this would be a great point to discuss at tomorrows' working group meeting! For example, should we go even further and just jump straight to GLWE, i.e., also combining LWE and RLWE ciphertexts?

**Comment by asraa** [comment]
I'll add it to our agenda! 

> For example, should we go even further and just jump straight to GLWE, i.e., also combining LWE and RLWE ciphertexts?

I remember we had some initial discussion about this. Let's revisit - I'll refresh my memory about our old conversation and see if those still apply. :)
