### ISSUE TITLE
thfe-rs-emitter: Runtime error when lower arith::ConstantOp

### ISSUE THREAD

**Issue by WoutLegiest** [google/heir#488]
Runtime error is throw when tests/tfhe-rust/ops.mlir is parsed by heir-translate

```bazel run //tools:heir-translate -- --emit-tfhe-rust-bool $(pwd)/tests/tfhe_rust/ops.mlir```

**Comment by asraa** [comment]
If you apply the changes here to the bool emitter, does it reproduce? 
https://github.com/google/heir/pull/480

**Comment by WoutLegiest** [comment]
Yes, changes can now produce trivial encryption

**Comment by WoutLegiest** [comment]
Yes, changes can now produce trivial encryption
