### ISSUE TITLE
Complete secret->bgv->OpenFHE end-to-end lowering path

### ISSUE THREAD

**Issue by j2kun** [google/heir#494]
This umbrella ticket tracks the overall ticket for lowering programs via BGV to OpenFHE

**Comment by j2kun** [comment]
Now that we have a lot of improved optimizations in this area, I will start to investigate end-to-end lowerings of the HECO evaluation artifacts through OpenFHE.

**Comment by j2kun** [comment]
Applying `secret-to-bgv` immediately after the simd optimizations complains about the tensor dimension.

```mlir
 bazel-bin/tools/heir-opt '--secretize=entry-function=linear_polynomial' --wrap-generic --canonicalize --cse --heir-simd-vectorizer --secret-to-bgv /home/j2kun/fhe/heir/tests/heir_simd_vectorizer/linear_polynomial_64.mlir
/home/j2kun/fhe/heir/tests/heir_simd_vectorizer/linear_polynomial_64.mlir:0:0: error: expected batched secret types to be tensors with dimension matching ring parameter
/home/j2kun/fhe/heir/tests/heir_simd_vectorizer/linear_polynomial_64.mlir:0:0: note: see current operation:
"builtin.module"() ({
  "func.func"() <{function_type = (!secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>) -> !secret.secret<tensor<64xi16>>, sym_name = "linear_polynomial"}> ({
  ^bb0(%arg0: !secret.secret<tensor<64xi16>>, %arg1: !secret.secret<tensor<64xi16>>, %arg2: !secret.secret<tensor<64xi16>>, %arg3: !secret.secret<tensor<64xi16>>):
    %0 = "secret.generic"(%arg0, %arg1, %arg2, %arg3) ({
    ^bb0(%arg4: tensor<64xi16>, %arg5: tensor<64xi16>, %arg6: tensor<64xi16>, %arg7: tensor<64xi16>):
      %1 = "arith.muli"(%arg4, %arg6) <{overflowFlags = #arith.overflow<none>}> : (tensor<64xi16>, tensor<64xi16>) -> tensor<64xi16>
      %2 = "arith.subi"(%1, %arg7) <{overflowFlags = #arith.overflow<none>}> : (tensor<64xi16>, tensor<64xi16>) -> tensor<64xi16>
      %3 = "arith.subi"(%2, %arg5) <{overflowFlags = #arith.overflow<none>}> : (tensor<64xi16>, tensor<64xi16>) -> tensor<64xi16>
      "secret.yield"(%3) : (tensor<64xi16>) -> ()
    }) : (!secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>, !secret.secret<tensor<64xi16>>) -> !secret.secret<tensor<64xi16>>
    "func.return"(%0) : (!secret.secret<tensor<64xi16>>) -> ()
  }) : () -> ()
}) : () -> ()
```

**Comment by AlexanderViand-Intel** [comment]
That makes sense, as the current batching pass simply uses the original vector sizes (e.g., `64`) and the secret-to-bgv lowering expects tensors of secrets to be of ring size. I think we already had a brief discussion about potential ways to bridge the gap, but let me try and make a more exhaustive list:

* Add a general vector size<->ring size adaption pass that implements the logic from, e.g., Microsoft EVA's extended vector library (part of "EVA Improved") and/or something based on the HELayers tiling approach.
* Make the batching pass somehow ring-size aware. This is easier said than done, though, and might require implementing something more generic, as in Viaduct HE.
* Change the batching pass so that it does not assume cyclical rotation. This should be relatively straight forward, as there's only  a few places that explicitly use the modular index arithmetic (e.g., the analysis and the rotation folds). The downside is that this produces noticeably worse code.
*  Only support powers of two as vector sizes, which can be handled by simply repeating the vector inside the ring during encoding/encryption. This is, iirc, what I ended up using for HECO, as it's trivial to implement and required no changes to batching passes.
* ... Any other approaches I missed?

**Comment by j2kun** [comment]
Another obstacle: ideally whatever modifies the input to resize things as appropriate for a particular FHE scheme must also provide an interface layer for the original code. I.e., if the user expects to pass a `tensor<64xi32>` to their input cleartext program, then the encrypted version must provide a means to encrypt a `tensor<64xi32>` to whatever type is input to the encrypted version of the function. Right now in CGGI that translation is implicit, but as we do more RNS and similar, we'll need to make that transformation more explicit.

**Comment by j2kun** [comment]
Scratch that, I can get it to run the lowering, if I hard code the vector size as a pass parameter:

```
'--secretize=entry-function=linear_polynomial' --wrap-generic --canonicalize --cse --heir-simd-vectorizer --secret-distribute-generic '--secret-to-bgv=poly-mod-degree=64'
```

Which produces an IR equivalent to

```mlir
!ct_ty = !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <cmod=463187969, ideal=#polynomial.polynomial<1 + x**64>>>>
!ct_sq_ty = !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <dimension = 3, ring = <cmod=463187969, ideal=#polynomial.polynomial<1 + x**64>>>>

module {
  func.func @linear_polynomial(%arg0: !ct_ty, %arg1: !ct_ty, %arg2: !ct_ty, %arg3: !ct_ty) -> !ct_ty {
    %0 = bgv.mul(%arg0, %arg2) : !ct_ty -> !ct_sq_ty
    %1 = bgv.relinearize(%0) {from_basis = array<i32: 0, 1, 2>, to_basis = array<i32: 0, 1>} : !ct_sq_ty -> !ct_ty
    %2 = bgv.sub(%arg3, %1) : !ct_ty
    %3 = bgv.sub(%2, %arg1) : !ct_ty
    return %3 : !ct_ty
  }
}
```

**Comment by asraa** [comment]
> Scratch that, I can get it to run the lowering, if I hard code the vector size as a pass parameter:

Hey! Yes, this was my doing. I expected that a pre-pass would handle 
* Determine the ideal N, q values for security / correctness
* Handle a rewrite for the appropriate padding and tiling for the input tensors similar to what Alex described above

RE the input handling you mentioned above: we will already change the function signature at some point to also have the bootstrapping key - I think it would probably make sense to change the function signature (and keep the original as an attribute?), and create a client-side helper that takes the original input and encodes and encrypts it to the correct signature.

**Comment by j2kun** [comment]
Returning to this with the following outline:

- Add a `bgv-add-client-interface` that adds encrypt/decrypt functions around the compiled entry function, so that we can preserve the coherence of the lowered types through the IR (I ran into this problem when trying to lower `simple_sum` which has type `tensor<32xi16> -> i16`, but the compiled type is just `ciphertext -> ciphertext`.
- Properly lower `bgv.extract` which currently has no lowering from `bgv`.
- Add bgv encrypt/decrypt and also lower them to openfhe.
- Improve the openfhe testing harness to work with these improvements.

That should complete this ticket, and we can use it to test the various tensor_ext passes for correctness.

**Comment by j2kun** [comment]
Thinking out loud as I work through some of my issues lowering bgv.extract.

Right now the `bgv.extract` op is asserting the input `underlying_type` on a ciphertext goes from a tensor to a scalar. This makes sense, except once we try to lower it to openfhe: `extract` lowers to a multiplication with a one-hot plaintext, followed by a rotate, but these all preserve the tensor `underlying_type`, and there's no way to get it back to a scalar. In other words, once we get to the openfhe API, the only thing that maintains the interpretation of the underlying type is the decrypt helper added by `bgv-add-client-interface`.

So to proceed, I think I will relax the requirements on `bgv.extract`, so that it can output an "underlying type" that is either a tensor or a scalar, and then "upgrade" the scalar to a tensor during `bgv-add-client-interface`. This may produce a problem later if we have other BGV backends that are aware of the underlying type, in which case we would need to convert the `bgv` part of `bgv-add-client-interface` to an openfhe-aware variant.

**Comment by j2kun** [comment]
An alternative is to introduce some sort of "cast" op that just changes the underlying type.

**Comment by j2kun** [comment]
I will go with the `cast` approach, and now I'm realizing I also need to enhance `add-client-interface` to support public-key encryption, since that is what openfhe uses.

**Comment by j2kun** [comment]
Remaining improvements are split into their own issues.
