### ISSUE TITLE
Achieve the optimum rotations for insert-rotate on a simple_sum example

### ISSUE THREAD

**Issue by j2kun** [google/heir#520]
E.g., 

```mlir
$  bazel run //tools:heir-opt -- --secretize=entry-function=simple_sum --wrap-generic --canonicalize --cse --full-loop-unroll --insert-rotate --cse --canonicalize --rotate-and-reduce --canonicalize <<EOF
func.func @simple_sum(%arg0: tensor<32xi16> {secret.secret}) -> i16 {
  %c0 = arith.constant 0 : index
  %c0_si16 = arith.constant 0 : i16
  %0 = affine.for %i = 0 to 32 iter_args(%sum_iter = %c0_si16) -> i16 {
    %1 = tensor.extract %arg0[%i] : tensor<32xi16>
    %2 = arith.addi %1, %sum_iter : i16
    affine.yield %2 : i16
  }
  return %0 : i16
}
EOF
```

Should produce an IR with log2(32) = 5 rotations. Perhaps this means `rotate-and-reduce` takes priority before `insert-rotate`, perhaps it means `rotate-and-reduce` should be smarter, perhaps it means `--insert-rotate` should be smarter, or perhaps it means that a pass should happen in between the two to make `rotate-and-reduce` easier to detect the reduction.

**Comment by AlexanderViand-Intel** [comment]
In HECO, we first do the `n-ary` grouping, then the rotation batching, then lower any suitable `n-ary` ops that are left to rotate-and-reduce. I think you could achieve the same effect by having `--insert-rotate` look ahead until it either finds (a) an insert operation, the index of which becomes the target slot or  (b) a non-matching arithmetic operation (in which case the target index is undefined). With a bit of luck, that should emulate the effect of having the arithmetic ops grouped without actually having to group them

**Comment by j2kun** [comment]
@AlexanderViand-Intel I think I figured out why our numbers were different. The version of box_blur I was using from HECO's test files was actually a 3x3 kernel, closer to the Gaussian blur from your paper's Listing 3 (note the `affine.for %j = -1 to 2` instead of `affine.for %j = -1 to 1`)

```
 func.func @box_blur(%arg0: tensor<16xi16> {secret.secret}) -> tensor<16xi16> {
    %c16 = arith.constant 16 : index
    %c4 = arith.constant 4 : index
    %0 = affine.for %x = 0 to 4 iter_args(%arg0_x = %arg0) -> (tensor<16xi16>) {
      %1 = affine.for %y = 0 to 4 iter_args(%arg0_y = %arg0_x) -> (tensor<16xi16>) {
        %c0_si16 = arith.constant 0 : i16
        %2 = affine.for %j = -1 to 2 iter_args(%value_j = %c0_si16) -> (i16) {
          %6 = affine.for %i = -1 to 2 iter_args(%value_i = %value_j) -> (i16) {
            %7 = arith.addi %x, %i : index
            %8 = arith.muli %7, %c4 : index
            %9 = arith.addi %y, %j : index
            %10 = arith.addi %8, %9 : index
            %11 = arith.remui %10, %c16 : index
            %12 = tensor.extract %arg0[%11] : tensor<16xi16>
            %13 = arith.addi %value_i, %12 : i16
            affine.yield %13 : i16
          }
          affine.yield %6 : i16
        }
        %3 = arith.muli %c4, %x : index
        %4 = arith.addi %3, %y : index
        %5 = arith.remui %4, %c16 : index
        %6 = tensor.insert %2 into %arg0_y[%5] : tensor<16xi16>
        affine.yield %6 : tensor<16xi16>
      }
      affine.yield %1 : tensor<16xi16>
    }
    return %0 : tensor<16xi16>
```

In that case, 8 rotations is the optimum. I will go ahead and port the demo programs from the evaluation directory (though I'm not sure what the optimum is for all of them since the intermediate IRs are not checked in.

**Comment by AlexanderViand-Intel** [comment]
> @AlexanderViand-Intel I think I figured out why our numbers were different. The version of box_blur I was using from HECO's test files was actually a 3x3 kernel, closer to the Gaussian blur from your paper's Listing 3 (note the `affine.for %j = -1 to 2` instead of `affine.for %j = -1 to 1`)

Ohh, that makes sense - we were using 3x3 Kernels because that's what we thought porcupine used, but then we got the generated code snippets from them and it turned out their boxblur was 2x2. Clearly, some of the 3x3 stuff survived in `test/`.

> In that case, 8 rotations is the optimum. I will go ahead and port the demo programs from the evaluation directory (though I'm not sure what the optimum is for all of them since the intermediate IRs are not checked in.

If it helps, I can re-run the `evaluation/` stuff without the `emitC` stages and post the resulting `fhe`-level code.
