### ISSUE TITLE
Write canonicalization patterns for NTT/INTT

### ISSUE THREAD

**Issue by j2kun** [google/heir#542]
In particular, immediate ntt/intt pairs can be elided. Depends on https://github.com/google/heir/issues/182

**Comment by Maokami** [comment]
I've created a simple canonicalization pass: `NTT(INTT(x)) => x` and `INTT(NTT(x)) => x`.

Now, I started thinking that it would be good to have the following optimization pass as well:
`INTT(Op(NTT(x1), NTT(x2))) => Op(x1, x2)` where `Op = polynomial.add/sub/mul_scalar` (and the version with NTT and INTT switched.)

Should this be included in the canonicalization pass, or should I create a new pass for it? 😃

**Comment by j2kun** [comment]
I think this second pattern will be a bit more complicated, since Op will be a tensor op in one domain and a polynomial op in the other, and it is context dependent which is cheaper (since it depends on what other neighboring ops are doing, if they are in the coefficient or NTT domain)

**Comment by j2kun** [comment]
I think the right approach to figure out what to do next is:

1. Add a pass that actually introduces ntt/intt ops by replacing polynomial.mul with ntt + tensor mul + intt.
2. Analyze some natural programs involving polynomial multiplications to look for optimization opportunities. Ideally we can do this by lowering some high level programs from BGV to polynomial, but that will involve a lot of extra work to actually implement bgv operations.

That or, comb through the HEaaN.mlir paper looking for optimizations related to this: https://dl.acm.org/doi/pdf/10.1145/3591228

**Comment by Maokami** [comment]
> I think this second pattern will be a bit more complicated, since Op will be a tensor op in one domain and a polynomial op in the other, and it is context dependent which is cheaper (since it depends on what other neighboring ops are doing, if they are in the coefficient or NTT domain)

Ah, you are right! This requires considering much more complex factors than I thought.

I'll tackle the task 1(making a (i)ntt introducing pass) and then skim through the HEaaN.mlir optimizations. 👍

**Comment by j2kun** [comment]
I filed a separate issue for HEaaN.mlir, and we can limit this issue to the basic canonicalization patterns: https://github.com/google/heir/issues/635

I think loop fusion would be a good place to start. CC @inbelic since he is working on the initial ntt lowering.

**Comment by inbelic** [comment]
Sweet. Feel free to ask me any questions on how it is implemented.

There is also a (messy) initial implementation of turning poly.mul into ntt ops [here] (https://github.com/inbelic/heir/commit/2e0f6d5682060b5d1b72bd4a8838398d35d861c3). You can patch that to do some analysis with it.

**Comment by j2kun** [comment]
Cc @Maokami to avoid double work

**Comment by Maokami** [comment]
Awesome! Thank you everyone for letting me know and I'll move on to the new issue now :)

**Comment by arcturusannamalai** [comment]
Safer-MLIR paper also talks about the optimization of forward and inverse NTT using distributive property, using CSE pass, and using all operator/operands in expression in transform domain to eliminate unneeded forward and inverse NTTs.
It gets complicated to get these constraints into code but well worth it in Heir

**Comment by j2kun** [comment]
> Safer-MLIR paper ... 

Could you link to this paper? I don't recall it.

**Comment by AlexanderViand-Intel** [comment]
> > Safer-MLIR paper ...
> 
> Could you link to this paper? I don't recall it.

Maybe [SyFER-MLIR](https://math.mit.edu/research/highschool/primes/materials/2020/Govindarajan-Moses.pdf)? They do discuss a few things around NTT, iirc, but mostly things you get "for free" with MLIR which we already do (cse, folding away ntt(intt(x)) and intt(ntt(x), etc).  They do also do things such as moving (i)NTTs through additions (i.e. `ntt(a) + ntt(b)` becomes `ntt(a+b)`), which is probably a "safe" rewrite (most reasonable backends shouldn't show a performance difference between add in coeff form and eval form).

**Comment by arcturusannamalai** [comment]
I'm sorry about the typo/auto-correct; it is indeed Syfer-MLIR.
@AlexanderViand-Intel - the paper moves out n-invocations of FFT and IFFT; this is important and not come for free from MLIR AFAIK

**Comment by j2kun** [comment]
> I'm sorry about the typo/auto-correct; it is indeed Syfer-MLIR. @AlexanderViand-Intel - the paper moves out n-invocations of FFT and IFFT; this is important and not come for free from MLIR AFAIK

So the only FHE-specific optimization I see from their paper is canceling ntt(intt(x)) and intt(ntt(x)), as Alex mentioned, which we already have from https://github.com/google/heir/pull/631

We should add Alex's additional suggested pattern (`ntt(a) + ntt(b) = ntt(a+b)`). I suggested in an earlier comment that this optimization depends on what's going on around it, but for add/sub I think it should be always more optimal since add is equivalently expensive in each domain.

**Comment by j2kun** [comment]
Unless there are any more specific canonicalization patterns we think we can add for ntt/intt, I think we can close this issue.

**Comment by j2kun** [comment]
I will close this issue, but note that until I get https://github.com/google/heir/pull/675 working and merged (upstreaming polynomial) the new pattern won't apply.
