### ISSUE TITLE
Support non-tensor types as input to `lwe.rlwe_encode` in lowerings to BGV/OpenFHE

### ISSUE THREAD

**Issue by j2kun** [google/heir#646]

**Comment by asraa** [comment]
The linked issue #645 also describes how to encode short tensors - I suspect this will be handled by layout assignments / packing techniques to determine padding and replication strategies.

In the meantime, I'm adding support for scalars as replicated in plaintext slots, which will ensure correct behavior for scalar programs (i'll send a PR in a sec, happy to hear feedback)
