### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by crockeea** [google/heir#693]
Steps:
1. Clone the repo (commit `c070cf34f195a5fd9dbbbf95533f5b2e350fd01d`)
2. `bazel build @heir//tools:heir-opt`

This produces an error:
```
lib/Transforms/YosysOptimizer/LUTImporter.cpp: In member function 'virtual llvm::SmallVector<Yosys::RTLIL::SigSpec> mlir::heir::LUTImporter::getInputs(Yosys::RTLIL::Cell*) const':
lib/Transforms/YosysOptimizer/LUTImporter.cpp:62:10: error: could not convert 'reversed' from 'SmallVector<[...],4>' to 'SmallVector<[...],1>'
   62 |   return reversed;
      |          ^~~~~~~~
      |          |
      |          SmallVector<[...],4>
Target //tools:heir-opt failed to build
```

**Comment by AlexanderViand-Intel** [comment]
Ah, yes, this is the same gcc(11.4.0)-vs-clang issue I ran into a week or two ago. Let me create a PR with the fix, but for the moment you should be able to compile this by switching to clang instead of gcc (probably a good idea anyway when working with llvm).
