### ISSUE TITLE
Canonicalize `cggi.lut2` and `cggi.lut3` as `cggi.lut_lincomb`

### ISSUE THREAD

**Issue by j2kun** [google/heir#708]
This is mainly for duplicate code removal.

This requires adding lowerings for `cggi.lut_lincomb` everywhere we have lowerings for `lut2, lut3`, removing the lowerings for `lut2, lut3`, and ensuring `--canonicalize` is run to apply the canonicalization rules.

**Comment by ai-mannamalai** [comment]
would you want to keep the parameter 2, 3 as an attribute on lincomb ?

**Comment by j2kun** [comment]
I don't think the attribute is necessary at all, because `lut_lincomb` has variadic operands.

**Comment by ai-mannamalai** [comment]
should this issue be considered closed ?

**Comment by j2kun** [comment]
Yes, if you put a phrase like "Fixes #708" in the PR description it will automatically close the issue. Looks like the magic "Fixes" was not included: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by ai-mannamalai** [comment]
OK – thanks for the tip

From: Jeremy Kun ***@***.***>
Date: Friday, August 16, 2024 at 9:21 AM
To: google/heir ***@***.***>
Cc: Muthu Annamalai ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [google/heir] Canonicalize `cggi.lut2` and `cggi.lut3` as `cggi.lut_lincomb` (Issue #708)

Yes, if you put a phrase like "Fixes #708<https://github.com/google/heir/issues/708>" in the PR description it will automatically close the issue. Looks like the magic "Fixes" was not included: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests<https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests>
