### ISSUE TITLE
polynomial: upstream lowerings

### ISSUE THREAD

**Issue by j2kun** [google/heir#723]
After https://github.com/google/heir/issues/256, the polynomial dialect is now upstream. The remaining work is to upstream the passes

- convert-polynomial-mul-to-ntt
- polynomial-to-standard

Should start by giving our versions of these passes non-conflicting names with the upstream versions.

**Comment by AlexanderViand-Intel** [comment]
See also  #724 for how we might want to modify ` --convert-polynomial-mul-to-ntt` to be more accelerator friendly
