### ISSUE TITLE
test: re-enable openfhe end to end tests after #727 is fixed upstream

### ISSUE THREAD

**Issue by asraa** [google/heir#729]

**Comment by j2kun** [comment]
Here is the upstream WIP https://github.com/llvm/llvm-project/pull/94838

So far I've reproduced the error but don't know how to fix it.

**Comment by j2kun** [comment]
Can reenable once https://github.com/llvm/llvm-project/pull/96242 is integrated

**Comment by j2kun** [comment]
The upstream fix is merged, but I'm still getting segfaults.
