### ISSUE TITLE
Add pre-commit hook configuration to enforce style guide

### ISSUE THREAD

**Issue by j2kun** [google/heir#76]
https://pre-commit.com/hooks.html

e.g., under [hooks](https://pre-commit.com/hooks.html) it supports stuff like bazel-buildifier, clang-format, etc.

**Comment by asraa** [comment]
We probably also want to make a CI check for this too, just in case pre-commit hooks are faulty or something else happens

**Comment by j2kun** [comment]
According to the docs on the pre-commit site, all you have to do is register a workflow with a canned action and it will automatically pull in the precommit config and check them.
