### ISSUE TITLE
Add an (optional) pass parameter to `--convert-elementwise-to-affine` to restrict it to certain dialects and/or operations

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#768]
Currently, `--convert-elementwise-to-affine` applies to all `ElementwiseMappable` operations with `RankedTensorType` operands. 
This is fine for the current intended usage in HEIR, but the pass would be more widely useable with this added feature.

**Comment by j2kun** [comment]
This can probably borrow from the secret-distribute-generic pass. Cf. https://github.com/google/heir/blob/main/lib/Dialect/Secret/Transforms/Passes.td#L38-L39 and https://github.com/google/heir/blob/main/lib/Dialect/Secret/Transforms/DistributeGeneric.cpp#L494-L495 for how we did this before, and adding a dialect option should be straightforward.

**Comment by ahmedshakill** [comment]
Hi, I added the options to restrict the ops and/or dialects for the `--convert-elementwise-to-affine` pass. Should I add separate tests for this?

**Comment by AlexanderViand-Intel** [comment]
> Hi, I added the options to restrict the ops and/or dialects for the `--convert-elementwise-to-affine` pass. Should I add separate tests for this?

Thanks! Yes, adding a test would be great - looking forward to your PR!

**Comment by AlexanderViand-Intel** [comment]
> Should this be the default behavior to always pass the parameters to restrict which dialects to run the pass on. Or should we also keep the previous behavior so that the pass is run on all dialects and ops when not restricted?

I think it'd be great to have it default to the old behavior if no parameters are specified (i.e., make the parameters optional)
