### ISSUE TITLE
Make "nightly" binaries available

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#772]
While I'm guessing that currently, most people looking at HEIR are interested in actually *working on* the compiler, as we fill out more and more reasonable compilation paths from high-level to various targets, we'll probably start to have some people who are mostly interested in *using* HEIR to actually compile something. This could even be true for developers who are primarily interested in working on frontend/target support and don't need to do anything with HEIR itself except generate/parse MLIR. 

Since getting HEIR compiled from source requires quite a bit of both developer time (e.g., getting bazel) and CPU time (compiling LLVM) and we're already building the project on CI multiple times a day for the `build_and_test` action, I was wondering if we could put together an action to push a nightly binary release (at least for amd64 unix, which is I think the target the CI already builds anyway?) for `heir-opt`, `heir-translate` and `heir-lsp`?

**Comment by j2kun** [comment]
One thing that MLIR folks mentioned to me was that `mlir-opt` is a debugging tool, and that a proper released binary would likely have a different entrypoint binary with pared down features (e.g., we don't compile to GPU yet, so we could omit the GPU dialects and lowerings) and HEIR-specific help text, etc.

I think this will be necessary to some extent just for performance. The current `heir-opt` binary is 1.7G when compiled in debug mode. I imagine it would still be a hefty binary when compiled with `-c opt`, but I don't have that number offhand.

**Comment by asraa** [comment]
> Since getting HEIR compiled from source requires quite a bit of both developer time (e.g., getting bazel) and CPU time (compiling LLVM)

I think Alex might be saying it would be nice to have a nightly binary that people can use as they get started to avoid the onboarding time if they're just curious to reproduce or test out flows. I'm in support for a nightly CI job that we explicitly do mark as "NOT PRODUCTION QUALITY" at all. The workflow should be pretty easy to write and we can just upload it on GitHub artifacts.

> The current heir-opt binary is 1.7G when compiled in debug mode. I imagine it would still be a hefty binary when compiled with -c opt, but I don't have that number offhand.

Yeah, that's a good concern... I'm running an opt mode build right now, will update this post.

We can also probably trim out the call to registerAllDialects/registerAllPasses from MLIR upstream.

**Comment by asraa** [comment]
> Yeah, that's a good concern... I'm running an opt mode build right now, will update this post.

Opt mode build gives me 148M, compared to 2.9G when I build with debug on my device. I'm not totally sure why I have such a large debug build... but the opt mode is way, way smaller

**Comment by AlexanderViand-Intel** [comment]
Yep, as Asra said, this is just intended as a convenience, not as a replacement for eventually putting together a "real" interface for the compiler (though I guess we'll need better frontend support before that really makes sense anyway).

I didn't realize how crazy large the debug binaries where, but 148M sounds pretty reasonable for a nightly, thanks for trying it out!

**Comment by j2kun** [comment]
@asraa do you have any strong opinions on what to do here? I'm imagining:

- Create a `nightly` release tag 
- GH workflow to build the release at 12AM
- Find some existing GH action that will upload the binary to a new GH release and set the tag
- Delete old nightly's somehow

**Comment by asraa** [comment]
Let's probably also add the hash of the builds in the release comments, just to make sure they aren't stale

**Comment by asraa** [comment]
Nice! you got it, i'll review :)

**Comment by j2kun** [comment]
We'll see if https://github.com/google/heir/pull/775 is any good :)

**Comment by AlexanderViand-Intel** [comment]
> We'll see if #775 is any good :)

Looks great, thanks!

**Comment by asraa** [comment]
This looks pretty good! https://github.com/google/heir/releases/tag/nightly

I'll probably just add a little more to the body including the checksums for the binaries just so someone can make sure they're not stale (in case a nightly release failed)

**Comment by j2kun** [comment]
I was able to download the binary and run it on my system.
