### ISSUE TITLE
Add Documentation for `MulDepthAnalysis`

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#780]
I didn't notice this when the PR was up, but `MulDepthAnalysis.h` does not have any documentation (no comments on `class MulDepth` for IDE's/doc generators to pick up).  For comparison, see `TargetSlotAnalysis.h` or `RotationAnalysis.h`. 

While the MulDepth analysis is a straight forward concept, we should still to document a few things, e.g., what counts as a multiplication (recall the discussion we had about plaintext/scalar muls).

Original PR: 
* #760

**Comment by Maokami** [comment]
Good point! I will do that as soon as possible.
