### ISSUE TITLE
Issues with Bazel & ccache 

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#80]
If, like me, you're using [ccache](https://ccache.dev/) to significantly speed up clean rebuilds and other edge cases, you'll probably run into this problem: https://stackoverflow.com/questions/52370202/how-to-get-bazel-ccache-and-sandboxing-to-work-together-ccache-read-only-file

For me, in fact this, required also adding another directory, which you can get from either the error messages you'll, or by running `ccache -p` and looking what is set as `temporary_dir`.

For me, I then also had issues with bazel crashing because `$HOME` failed it's internal "must be an absolute path" which made bazel throw an exception and dump the stack 🤪 

This is what my `.bazelrc` ended up looking like
```
common --sandbox_writable_path=/run/user/1000/ccache-tmp --sandbox_writable_path=/home/vianda/.cache
```

**Comment by j2kun** [comment]
I don't use ccache (but maybe I should). Is this something that you think we should add generically to the project config? Getting the shell interpolation for `ccache --get-config temporary_dir` and `$HOME/cache` would require a slight [layer of indirection](https://github.com/bazelbuild/bazelisk#toolsbazel), but it's definitely doable.

**Comment by AlexanderViand-Intel** [comment]
I don't think use of `ccache` is widespread enough to warrant including this, this issue is more so that people with similar issues can find the solution/workaround.

**Comment by AlexanderViand-Intel** [comment]
More reasons not to try and integrate this workaround into the repo: when (for whatever reason) the directories don't exist yet (e.g., `ccache` hasn't created them yet), `bazel` will actually complain about the directory not existing and fail when trying to create the sandbox....
