### ISSUE TITLE
--wrap-generic rewrapping code already in secret.generic

### ISSUE THREAD

**Issue by MeronZerihun** [google/heir#809]
I am not sure if this is a behavior of any benefit but found it worth mentioning. I had a code region already secretized and wrapped by `secret.generic`. I ran secretize + wrap-generic again and found that the resulting MLIR code does contain another `secret.generic` wrapping around the existing secret.generic code. Here's the MLIR code and the command I ran:
```llvm
// input program
func.func @simple_if(%arg0: !secret.secret<i1>, %arg1: !secret.secret<i16>) -> !secret.secret<i16> {
    %0 = secret.generic ins(%arg0, %arg1 : !secret.secret<i1>, !secret.secret<i16>) {
    ^bb0(%arg2: i1, %arg3: i16):
      %1 = scf.if %arg2 -> (i16) {
        %2 = arith.addi %arg3, %arg3 : i16
        scf.yield %2 : i16
      } else {
        %2 = arith.muli %arg3, %arg3 : i16
        scf.yield %2 : i16
      }
      secret.yield %1 : i16
    } -> !secret.secret<i16>
    return %0 : !secret.secret<i16>
  }

// output I got
func.func @simple_if(%arg0: !secret.secret<!secret.secret<i1>>, %arg1: !secret.secret<!secret.secret<i16>>) -> !secret.secret<!secret.secret<i16>> {
    %0 = secret.generic ins(%arg0, %arg1 : !secret.secret<!secret.secret<i1>>, !secret.secret<!secret.secret<i16>>) {
    ^bb0(%arg2: !secret.secret<i1>, %arg3: !secret.secret<i16>):
      %1 = secret.generic ins(%arg2, %arg3 : !secret.secret<i1>, !secret.secret<i16>) {
      ^bb0(%arg4: i1, %arg5: i16):
        %2 = scf.if %arg4 -> (i16) {
          %3 = arith.addi %arg5, %arg5 : i16
          scf.yield %3 : i16
        } else {
          %3 = arith.muli %arg5, %arg5 : i16
          scf.yield %3 : i16
        }
        secret.yield %2 : i16
      } -> !secret.secret<i16>
      secret.yield %1 : !secret.secret<i16>
    } -> !secret.secret<!secret.secret<i16>>
    return %0 : !secret.secret<!secret.secret<i16>>
  }
```

Command I ran:
```bash
bazel run //tools:heir-opt -- --secretize=entry-function="simple_if" --wrap-generic --canonicalize <MLIR FILE NAME>
```

**Comment by AlexanderViand-Intel** [comment]
To me, the weird thing here isn't that this happens in the first place, but that the canonicalization doesn't get rid of the redundant double-wrap...

**Comment by j2kun** [comment]
This seems like a bug. I don't think it makes sense to nest secret.generic.

**Comment by asraa** [comment]
> To me, the weird thing here isn't that this happens in the first place, but that the canonicalization doesn't get rid of the redundant double-wrap...

In the future we probably do want to add some folding here for this, since I can imagine if we have secret types with attributes indicated a key ID or party ID that we could have double-wrapped secret types with attributes.

**Comment by asraa** [comment]
> This seems like a bug. I don't think it makes sense to nest secret.generic.

I bet the bug is in my secretize code for adding secret.secret attributes to non-plaintext arguments. It's an easy fix! One sec. :)
