### ISSUE TITLE
Fixing the nightly build

### ISSUE THREAD

**Issue by WoutLegiest** [google/heir#813]
https://github.com/google/heir/actions/runs/10050313017/job/27777982734

**Comment by AlexanderViand-Intel** [comment]
Unfortunately, it seems like even with the fix from @asraa, something is still going wrong, as the current "nightly" release says it's from 3 weeks ago?

**Comment by asraa** [comment]
weird! packages write was supposed to fix the perm error. Let me actually debug this (and probably add a step to post an issue automatically if there's a failure so we can tell when it's broken)

**Comment by j2kun** [comment]
https://github.com/google/heir/releases/tag/nightly hooray!
