### ISSUE TITLE
Support Ciphertext-Plaintext (Ctxt-Ptxt) Operations

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [google/heir#826]
~~Currently, FHE scheme ops like `bgv.mul/add/etc` require both operands to be ciphertexts. However,~~ 
(RLWE-style) FHE programs frequently perform ctxt-ptxt operations because they're more efficient and have lower noise growth. 

~~In addition to updating the type constraints,~~ this requires updating `--secret-to-bgv` to handle such cases.

EDIT: Not sure how I missed the `mul_plain`/etc ops in BGV, updated to reflect that they already exist

**Comment by j2kun** [comment]
Just FYI, the ops for this exist already in BGV

**Comment by asraa** [comment]
I believe there's mul/add_plain: I think I just mostly left out cptxt-ptxt lowering in secret-to-bgv!
