### ISSUE TITLE
yosys-optimizer error: abc: No such file or directory

### ISSUE THREAD

**Issue by asraa** [google/heir#861]
Running bazel test works fine on tests exercising yosys optimizer, since we override the abc binary path in the lit config, but it doesn't seem to work when invoking bazel run on the open source repository.

(It works internally, so I only just noticed this issue when debugging a PR)

Error:
```
13.1.1. Executing ABC.
Running ABC command: "bazel-out/k8-dbg/bin/external/edu_berkeley_abc/abc" -s -f <abc-temp-dir>/abc.script 2>&1
ABC: sh: line 1: bazel-out/k8-dbg/bin/external/edu_berkeley_abc/abc: No such file or directory
ERROR: ABC: execution of command ""bazel-out/k8-dbg/bin/external/edu_berkeley_abc/abc" -s -f /tmp/yosys-abc-19tW3o/abc.script 2>&1" failed: return code 127.
```

The abc path is retrieved from the bazel location make variable https://github.com/google/heir/blob/dd08bd681c97739a0208491cab3af296587632ee/tools/BUILD#L28, and the file at the path from the error exists and runs, so I suspect there's an issue with the relative path the ABC command might be expecting.

**Comment by j2kun** [comment]
I do bazel run on the OSS repo all the time...

**Comment by asraa** [comment]
This diff made things work
```
diff --git a/tools/BUILD b/tools/BUILD
index c3364d0b..66459d4b 100644
--- a/tools/BUILD
+++ b/tools/BUILD
@@ -25,7 +25,7 @@ cc_binary(
     # an escaped quote).
     defines = select({
         "@heir//:config_enable_yosys": [
-            "HEIR_ABC_BINARY=\\\"$(location @edu_berkeley_abc//:abc)\\\"",
+            "HEIR_ABC_BINARY=\\\"$(rootpath @edu_berkeley_abc//:abc)\\\"",
             "HEIR_YOSYS_SCRIPTS_DIR=\\\"" + WORKSPACE_PATH + "lib/Transforms/YosysOptimizer/yosys\\\"",
         ],
         "//conditions:default": ["HEIR_NO_YOSYS=1"],
```

where apparently rootpath will give me the path relative to the subdirectory of the runfiles
