### ISSUE TITLE
Broken templating on docs website

### ISSUE THREAD

**Issue by georgerennie** [google/heir#956]
Some of the diagrams and other templated features seem to have stopped working on hier.dev, such as the following from the homepage
![image](https://github.com/user-attachments/assets/d96b94f4-887d-4dff-aa8b-3e520cc1e8de)
and from https://heir.dev/community
![image](https://github.com/user-attachments/assets/3c92b245-e932-4b4f-bc9f-836d0443f167)

May be related to #925, not sure

**Comment by georgerennie** [comment]
Actually looking into it it seems like it happened with #937 and the markdown formatting is not preserving the hugo templates

**Comment by asraa** [comment]
Thank you! i think you're right - I found this related issue https://github.com/executablebooks/mdformat/issues/402 which seems like other people also complained but doesn't seem like there was a resolution. I think i have a workaround, i'll test it
